### PR TITLE
feat: add PrismicRichText, PrismicText, and PrismicEmbed

### PR DESCRIPTION
**Pull request by samlfair**
## Types of changes

- [ ] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR adds PrismicRichText, PrismicText, and PrismicEmbed. It also improves typings and TSDoc.

## Checklist:

- [ ] My change requires an update to the official documentation.
- [ ] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by samlfair** [comment]
@angeloashmore I'm getting a new type error on the SliceZone. Do you have a moment to take a look at it?

**Comment by angeloashmore** [comment]
Hey @samlfair, I pulled the latest version of the PR locally, but I'm not seeing any TypeScript errors in `src/lib/components/SliceZone.svelte` or in the example page that uses it.

Where are you seeing the error? Could you copy + paste or screenshot it?

**Comment by samlfair** [comment]
@angeloashmore I was still getting the TypeScript error, but I managed to fix it. I went through and typed everything, but when I was testing it I couldn't get my test app to find the type declarations. The components import fine, but without any typing.

image

I upgraded `@svelte/package`, which changes how Svelte bundles the package. The biggest change is that `dist/package.json` used to be automatically generated. Now you have to write your own `package.json` manually int he root directory, and the `package` command just copies it into `dist`. 

https://github.com/sveltejs/kit/discussions/8825

This didn't solve the problem. However, it did make me realize that I can fix the type declaration issue if I import from `@prismicio/svelte/dist`, which is frustrating.

image

Do you have any thoughts?

I've published this version as `@prismicio/svelte@dev` for testing.

**Comment by samlfair** [comment]
@angeloashmore I think I got the types working properly by editing `package.json`.

**Comment by samlfair** [comment]
@angeloashmore By using `svelteHTML.IntrinsicElement["a"]` and `["img"]`, we're losing all of our typing, and Svelte is typing props as `any` in the distributed package. I fixed this by switching to `import { HTMLAnchorAttributes, HTMLImgAttributes } from "svelte/elements"`, and now it's working fine. If you look at the component types in `dist/`, they are explicitly typed with every possible HTML or Svelte attribute as well as our Prismic-specific ones.

I also blocked users from using reserved properties (`src`, `srcset`, `href`).

I think this is ready to merge into master 🤞

**Pull request merged**
